spring:
  profiles:
    active: local
  application:
    name: kotlin-spring-webflux
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false # not suitable for ELK
        jdbc:
          lob:
            non_contextual_creation: true

