server:
  port: 9999

spring:
  application:
    name: kotlin-spring
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false # not suitable for ELK
        jdbc:
          lob:
            non_contextual_creation: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus